### ISSUE TITLE
The case for double occurrence

### ISSUE THREAD

**Issue by mmhamdy** [yyx990803/vue-wordle#3]
Hi 👋 Thanks for the awesome demo! 
I was curious about how Wordle deals with double occurrence of a letter in a word, didn't encounter such case.
But I did encounter one here and it's confusing...
![vvordle](https://user-images.githubusercontent.com/62081584/150682261-c12a530c-9b34-4a35-ba14-4d987c0f2eea.png)
According to the first and second tries, there should be 2 "e" in the final word, but there was only one.

**Comment by yyx990803** [comment]
Yeah, this has already been fixed in the latest deployed version.

**Comment by zhangenming** [comment]
How do I feel the original is more intuitive... https://github.com/yyx990803/vue-wordle/issues/7

>According to the first and second tries, there should be 2 "e" in the final word, but there was only one.


I don't think there's a problem with that
TE(green)E(yellow)TH
first green E, representative  E Exist and be right posstion..
second yellow E, representative  E Exist but not be right pos

I think it's better to keep the original
Do you think?
