### ISSUE TITLE
this is bug? answer is 'colon', but  'n' not color with yellow...tks

### ISSUE THREAD

**Issue by zhangenming** [yyx990803/vue-wordle#7]
![image](https://user-images.githubusercontent.com/21235555/150914860-d196884f-6972-422b-9a88-5ca4d417bac4.png)

**Comment by c-z-chen** [comment]
nah this is how it should work.. as long as you have a correct letter in correct place wordle will label it green, and the other one in the wrong place grey, for it is wrong whilst the word only contains one `N`; however if there are two `N`s in a word, the middle `N` should be yellow.

**Comment by zemmmmmmm** [comment]
So that's how the game works?
I also think it's kind of weird
